### ISSUE TITLE
Connect to uniswap-v2 subgraph errors

### ISSUE THREAD

**Issue by 0xCardiE** [graphprotocol/ethdenver-dapp#16]
I am trying to use the app to connect to https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
but I get some errors

```
{
  "graphQLErrors": [
    {
      "locations": [
        {
          "line": 1,
          "column": 17
        }
      ],
      "message": "Variable `where` must have an input type"
    },
    {
      "locations": [
        {
          "line": 1,
          "column": 43
        }
      ],
      "message": "Variable `orderBy` must have an input type"
    }
  ],
  "networkError": null,
  "message": "GraphQL error: Variable `where` must have an input type\nGraphQL error: Variable `orderBy` must have an input type"
}
```

Needs some guidance what to do as I was hoping from readme that we can connect this app to any subgraph and it would work out of the box :)
Do I need to setup some kind of schema to match?

**Comment by 0xCardiE** [comment]
Oh I get it now. This repo is tied to Gravatar contract and its entites. I need to change the app code to go with uniswap contract and entities indexed there.

**Comment by paulvi** [comment]
please close
